### ISSUE TITLE
error during building application

### ISSUE THREAD

**Issue by manang** [jitsi/jitsi-meet-electron#117]
I'm trying to build the application and I have the following error:

`MANANGEL-M-139C:j_electron angelomantellini$ npm install

> jitsi-meet-electron@1.0.0 postinstall /Users/angelomantellini/j_electron
> electron-builder install-app-deps

  • electron-builder version=20.28.1
  • loaded configuration file=package.json ("build" field)
  • rebuilding native production dependencies platform=darwin arch=x64
Error: /usr/local/Cellar/node/10.10.0/bin/node exited with code 6
Output:

> fsevents@1.2.4 install /Users/angelomantellini/j_electron/node_modules/fsevents
> node install

Error output:
node-pre-gyp ERR! Completion callback never invoked!
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.10.0/bin/node" "/Users/angelomantellini/j_electron/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/angelomantellini/j_electron/node_modules/fsevents
node-pre-gyp ERR! node -v v10.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! fsevents@1.2.4 install: `node install`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the fsevents@1.2.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/angelomantellini/.npm/_logs/2018-09-18T11_31_56_927Z-debug.log

    at ChildProcess.childProcess.once.code (/Users/angelomantellini/j_electron/node_modules/builder-util/src/util.ts:254:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
From previous event:
    at rebuild (/Users/angelomantellini/j_electron/node_modules/app-builder-lib/out/util/yarn.js:239:18)
    at /Users/angelomantellini/j_electron/node_modules/app-builder-lib/src/util/yarn.ts:20:11
From previous event:
    at installOrRebuild (/Users/angelomantellini/j_electron/node_modules/app-builder-lib/out/util/yarn.js:68:17)
    at /Users/angelomantellini/j_electron/node_modules/electron-builder/src/cli/install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
From previous event:
    at installAppDeps (/Users/angelomantellini/j_electron/node_modules/electron-builder/out/cli/install-app-deps.js:174:17)
    at then (/Users/angelomantellini/j_electron/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Object.args [as handler] (/Users/angelomantellini/j_electron/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at Object.runCommand (/Users/angelomantellini/j_electron/node_modules/yargs/lib/command.js:237:44)
    at Object.parseArgs [as _parseArgs] (/Users/angelomantellini/j_electron/node_modules/yargs/yargs.js:1059:30)
    at Object.get [as argv] (/Users/angelomantellini/j_electron/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/Users/angelomantellini/j_electron/node_modules/electron-builder/src/cli/cli.ts:25:28)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jitsi-meet-electron@1.0.0 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jitsi-meet-electron@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
How can I solve this issue?

**Comment by saghul** [comment]
Please **read** the error message. It clearly points out which package generated the error.
