### ISSUE TITLE
 npm install Error on windows10

### ISSUE THREAD

**Issue by TangXT** [jitsi/jitsi-meet-electron#134]
@saghul   I run npm install on windows10 It shows error as below:
26002 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
26003 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
26004 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
26004 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
26004 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
26004 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
26005 verbose stack Error: robotjs@github:jitsi/robotjs#5cc469f655669e728b61271c2c57ce97d62976fd install: `node-gyp rebuild`
26005 verbose stack Exit status 1
26005 verbose stack     at EventEmitter.<anonymous> (C:\Users\Douglas Tang\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
26005 verbose stack     at emitTwo (events.js:126:13)
26005 verbose stack     at EventEmitter.emit (events.js:214:7)
26005 verbose stack     at ChildProcess.<anonymous> (C:\Users\Douglas Tang\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
26005 verbose stack     at emitTwo (events.js:126:13)
26005 verbose stack     at ChildProcess.emit (events.js:214:7)
26005 verbose stack     at maybeClose (internal/child_process.js:925:16)
26005 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
26006 verbose pkgid robotjs@github:jitsi/robotjs#5cc469f655669e728b61271c2c57ce97d62976fd
26007 verbose cwd C:\jitsi-meet-electron
26008 verbose Windows_NT 10.0.17134
26009 verbose argv "C:\\nodejs\\node.exe" "C:\\Users\\Douglas Tang\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
26010 verbose node v8.11.3
26011 verbose npm  v6.4.1
26012 error code ELIFECYCLE
26013 error errno 1
26014 error robotjs@github:jitsi/robotjs#5cc469f655669e728b61271c2c57ce97d62976fd install: `node-gyp rebuild`
26014 error Exit status 1
26015 error Failed at the robotjs@github:jitsi/robotjs#5cc469f655669e728b61271c2c57ce97d62976fd install script.
26015 error This is probably not a problem with npm. There is likely additional logging output above.
26016 verbose exit [ 1, true ]

**Comment by saghul** [comment]
Do you have the Windows build tools installed? https://www.npmjs.com/package/windows-build-tools
