### ISSUE TITLE
fatal error: 'algorithm' file not found

### ISSUE THREAD

**Issue by abdurrahmanekr** [jitsi/jitsi-meet-electron#144]
I'm running this command:
```
npm install jitsi-meet-electron-utils
```
I'm getting this error:
```

> robotjs@0.4.7 install /Users/burak/Desktop/detaysoft/web/node_modules/jitsi-meet-electron-utils/node_modules/robotjs
> node-gyp rebuild

2018-10-26 13:47:50.056 xcodebuild[5025:62099] [MT] PluginLoading: Required plug-in compatibility UUID 8B9F56A7-4D8B-41AA-A65D-D4906CDF1539 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/xcfui.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ../src/robotjs.cc:2:
../../../../nan/nan.h:55:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
1 warning and 1 error generated.
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/burak/Desktop/detaysoft/web/node_modules/jitsi-meet-electron-utils/node_modules/robotjs
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```

My package.json:
```
{
  "name": "test",
  "version": "6.1.0",
  "private": true,
  "main": "main.js",
  "dependencies": {
    "jitsi-meet-electron-utils": "github:jitsi/jitsi-meet-electron-utils"
  },
  "devDependencies": {
  }
}
```

I'm using macOS Mojave. 
nodejs: v6.2.0
npm: 3.8.9

**Comment by saghul** [comment]
Please report it here: https://github.com/jitsi/jitsi-meet-electron-utils/issues
