### ISSUE TITLE
Not working developer mode

### ISSUE THREAD

**Issue by akalana** [jitsi/jitsi-meet-electron#154]
Node Version : `8.12.0`
Npm Version : `6.41`
Operating System : `Ubuntu 18.04`
jitsi-meet-electrom version: `846d742ccd7aca5e3689bdb852cf970745ab7946`

npm install works fine.
npm run dist woks fine

But npm start fails. I have attached the error log here

```sh
> jitsi-meet-electron@1.1.1 watch /home/akalana/jitsi-meet-electron
[watch] > webpack --config ./webpack.renderer.js --mode development --watch --watch-poll
[watch] 
[1] Electron could not be found. No hard resets for you!
[1] Attempted to load extension "React Developer Tools" that has already been loaded.
[watch] 
[watch] webpack is watching the files...
[watch] 
[watch] Hash: 083f7a6a2fda2335f256
[watch] Version: webpack 4.20.2
[watch] Time: 1079ms
[watch] Built at: 2018-12-20 16:23:59
[watch]      Asset       Size  Chunks             Chunk Names
[watch]     app.js   6.53 KiB     app  [emitted]  app
[watch] index.html  361 bytes          [emitted]  
[watch] Entrypoint app = app.js
[watch] [./app/index.js] 2.74 KiB {app} [built] [failed] [1 error]
[watch] 
[watch] ERROR in ./app/index.js
[watch] Module build failed (from ./node_modules/babel-loader/lib/index.js):
[watch] Error: [BABEL] /home/akalana/jitsi-meet-electron/app/index.js: Invalid Option: '^3.0.13' is not a valid value for 'targets.electron'. (While processing: "/home/akalana/jitsi-meet-electron/node_modules/@babel/preset-env/lib/index.js")
[watch]     at semverifyTarget (/home/akalana/jitsi-meet-electron/node_modules/@babel/preset-env/lib/targets-parser.js:153:11)
[watch]     at __default (/home/akalana/jitsi-meet-electron/node_modules/@babel/preset-env/lib/targets-parser.js:159:92)
[watch]     at Object.keys.filter.sort.reduce (/home/akalana/jitsi-meet-electron/node_modules/@babel/preset-env/lib/targets-parser.js:203:43)
[watch]     at Array.reduce (<anonymous>)
[watch]     at getTargets (/home/akalana/jitsi-meet-electron/node_modules/@babel/preset-env/lib/targets-parser.js:191:104)
[watch]     at _default (/home/akalana/jitsi-meet-electron/node_modules/@babel/preset-env/lib/index.js:187:46)
[watch]     at /home/akalana/jitsi-meet-electron/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
[watch]     at loadDescriptor (/home/akalana/jitsi-meet-electron/node_modules/babel-loader/node_modules/@babel/core/lib/config/full.js:165:14)
[watch]     at cachedFunction (/home/akalana/jitsi-meet-electron/node_modules/babel-loader/node_modules/@babel/core/lib/config/caching.js:33:19)
[watch]     at loadPresetDescriptor (/home/akalana/jitsi-meet-electron/node_modules/babel-loader/node_modules/@babel/core/lib/config/full.js:235:63)
[watch]     at config.presets.reduce (/home/akalana/jitsi-meet-electron/node_modules/babel-loader/node_modules/@babel/core/lib/config/full.js:77:21)
[watch]     at Array.reduce (<anonymous>)
[watch]     at recurseDescriptors (/home/akalana/jitsi-meet-electron/node_modules/babel-loader/node_modules/@babel/core/lib/config/full.js:74:38)
[watch]     at loadFullConfig (/home/akalana/jitsi-meet-electron/node_modules/babel-loader/node_modules/@babel/core/lib/config/full.js:108:6)
[watch]     at process.nextTick (/home/akalana/jitsi-meet-electron/node_modules/babel-loader/node_modules/@babel/core/lib/transform.js:28:33)
[watch]     at _combinedTickCallback (internal/process/next_tick.js:132:7)
[watch]     at process._tickCallback (internal/process/next_tick.js:181:9)
[watch] Child html-webpack-plugin for "index.html":
[watch]      1 asset
[watch]     Entrypoint undefined = index.html
[watch]     [./node_modules/html-webpack-plugin/lib/loader.js!./app/index.html] 521 bytes {0} [built]
[watch]     [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {0} [built]
[watch]         + 1 hidden module
```
Any pointers to tack this down ?

**Comment by saghul** [comment]
Can you try this PR? https://github.com/jitsi/jitsi-meet-electron/pull/152

**Comment by akalana** [comment]
Thank you very much.It works fine
