### ISSUE TITLE
Error in executing 'npm install' in my terminal while installing jitsi/jitsi-meet-electron.

### ISSUE THREAD

**Issue by vinay72** [jitsi/jitsi-meet-electron#162]
I have already tried running 'npm install --verbose' in my terminal but nothing is working out for me
as terminal is taking so much time to install node_modules in this project . Here is the screenshot
![screenshot from 2019-02-12 22-57-44](https://user-images.githubusercontent.com/28500944/52655633-9e1f0900-2f1a-11e9-908c-253a0c87874f.png)

**Comment by saghul** [comment]
You need to wait. Also, why are you running the install as root? There is no need to do that, and it can only cause trouble.

**Comment by vsvipul** [comment]
@saghul i tried to do an npm install and my installation also got stuck. Maybe, there is a problem?

**Comment by vsvipul** [comment]
During my installation, it gets stuck on 
```
[  ................] | fetchMetadata: sill pacote range manifest for is-finite@^1.0.0 fetched in 4ms
```
What should i do ? I have been waiting for half an hour and it still doesn't install..

**Comment by vsvipul** [comment]
@saghul i installed the app but on running npm start, it gives the following error. I need some help.
```
[path] external "path" 42 bytes {main} [built]
[url] external "url" 42 bytes {main} [built]
    + 198 hidden modules
[1] /home/vipul/Documents/jitsi-meet-electron/node_modules/electron/index.js:14
[1]     throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
[1]     ^
[1] 
[1] Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
[1]     at getElectronPath (/home/vipul/Documents/jitsi-meet-electron/node_modules/electron/index.js:14:11)
[1]     at Object.<anonymous> (/home/vipul/Documents/jitsi-meet-electron/node_modules/electron/index.js:18:18)
[1]     at Module._compile (module.js:652:30)
[1]     at Object.Module._extensions..js (module.js:663:10)
[1]     at Module.load (module.js:565:32)
[1]     at tryModuleLoad (module.js:505:12)
[1]     at Function.Module._load (module.js:497:3)
[1]     at Module.require (module.js:596:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/home/vipul/Documents/jitsi-meet-electron/node_modules/electron/cli.js:3:16)
[1] electron ./build/main.js exited with code 1
[watch] 
[watch] > jitsi-meet-electron@1.1.1 watch /home/vipul/Documents/jitsi-meet-electron
[watch] > webpack --config ./webpack.renderer.js --mode development --watch --watch-poll
[watch] 
[watch] 
[watch] webpack is watching the files...
[watch] 
[watch] Hash: e0cee2d2dbfc8d65ab25
[watch] Version: webpack 4.27.1
[watch] Time: 3776ms
[watch] Built at: 16/02/2019 9:08:08 PM
[watch]                                Asset       Size  Chunks             Chunk Names

```

Please help me run. Also, i want to start contributing to this repository, as soon as i can. Where can i find the chat chaneel or irc or any other method of communication that you guys use. Thanks

**Comment by damencho** [comment]
https://community.jitsi.org is the place for questions

**Comment by vsvipul** [comment]
Finally it worked after removing every package starting with electron and not just electron/ .. I would love to contribute to this project. Please point me to some easy beginner issues i can begin with. I have enough knowledge of electron.

**Comment by ouya99** [comment]
@vsvipul i am having the exact same issue with current jitsi-meet-electron. Removing all node-modules and re-installing did not help. What else did you do?

**Comment by ouya99** [comment]
ok solved it by using node 12, npm 6
1) rm package-lock.json
2) npm i 
3) npm i electron-rebuild
4) node_modules/.bin/electron-rebuild
5) npm start
