### ISSUE TITLE
Question: failed to introduce the project

### ISSUE THREAD

**Issue by zhangzhoufei** [jitsi/jitsi-meet-electron#184]
Error: The module '\?\G:\ZZF\electron-vue-template-SynchronizedUpdates\node_modules\jitsi-meet-electron-utils\node_modules\robotjs\build\Release\robotjs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using npm rebuild or npm install).
at process.func (electron/js2c/asar.js:138:31)
at process.func [as dlopen] (electron/js2c/asar.js:138:31)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
at Object.func (electron/js2c/asar.js:138:31)
at Object.func [as .node] (electron/js2c/asar.js:138:31)
at Module.load (internal/modules/cjs/loader.js:645:32)
at Function.Module._load (internal/modules/cjs/loader.js:560:12)
at Module.require (internal/modules/cjs/loader.js:685:19)
at require (internal/modules/cjs/helpers.js:16:16)
at Object. (G:\ZZF\electron-vue-template-SynchronizedUpdates\node_modules\jitsi-meet-electron-utils\node_modules\robotjs\index.js:1:15)

**Comment by saghul** [comment]
Duplicate.
