### ISSUE TITLE
Autoupdate failure - New version is not signed by the application owner

### ISSUE THREAD

**Issue by C0rn3j** [jitsi/jitsi-meet-electron#234]
Autoupdate seems to fail on a Windows machine of mine(using 1.1.1).
[Full log](https://haste.rys.pw/raw/cotefirape)

EDIT: This probably has to do with me setting a stricter ExecutionPolicy when I was [installing Chocolatey](https://chocolatey.org/install), but the error isn't displayed by Jitsi Meet in any way, the update just silently fails.
```
[22:25:05.125] [warn] Sign verification failed, installer signed with incorrect certificate: publisherNames: Atlassian Pty Ltd, raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "The file C:\\Users\\A\\AppData\\Roaming\\Jitsi Meet\\__update__\\temp-jitsi-meet.exe is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170"
}
[22:25:05.151] [error] Error: Error: New version 2.0.0-beta3 is not signed by the application owner: publisherNames: Atlassian Pty Ltd, raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "The file C:\\Users\\A\\AppData\\Roaming\\Jitsi Meet\\__update__\\temp-jitsi-meet.exe is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170"
}
    at t.newError (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:6089)
    at Object.<anonymous> (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:2:164185)
    at Generator.next (<anonymous>)
    at Generator.a (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:1297)
    at p._promiseFulfilled (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:155733)
    at x._settlePromise (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:105894)
    at x._settlePromise0 (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:106492)
    at x._settlePromises (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:107844)
    at p (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:109414)
    at f (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:109353)
    at u._drainQueues (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:110873)
    at Immediate.drainQueues [as _onImmediate] (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:109095)
From previous event:
    at x.j [as _captureStackTrace] (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:124897)
    at new p (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:154608)
    at C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:157697
    at t.NsisUpdater._checkForUpdates (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:32121)
    at t.NsisUpdater.checkForUpdates (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:30842)
    at t.NsisUpdater.checkForUpdatesAndNotify (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:31048)
    at App.m (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:95485)
    at App.emit (events.js:187:15)
Unhandled rejection Error: New version 2.0.0-beta3 is not signed by the application owner: publisherNames: Atlassian Pty Ltd, raw info: {
  "SignerCertificate": null,
  "TimeStamperCertificate": null,
  "Status": 2,
  "StatusMessage": "The file C:\\Users\\A\\AppData\\Roaming\\Jitsi Meet\\__update__\\temp-jitsi-meet.exe is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170"
}
    at t.newError (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:6089)
    at Object.<anonymous> (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:2:164185)
    at Generator.next (<anonymous>)
    at Generator.a (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:1297)
    at p._promiseFulfilled (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:155733)
    at x._settlePromise (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:105894)
    at x._settlePromise0 (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:106492)
    at x._settlePromises (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:107844)
    at p (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:109414)
    at f (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:109353)
    at u._drainQueues (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:110873)
    at Immediate.drainQueues [as _onImmediate] (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:109095)
From previous event:
    at x.j [as _captureStackTrace] (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:124897)
    at new p (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:154608)
    at C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:157697
    at t.NsisUpdater._checkForUpdates (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:32121)
    at t.NsisUpdater.checkForUpdates (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:30842)
    at t.NsisUpdater.checkForUpdatesAndNotify (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:31048)
    at App.m (C:\Users\A\AppData\Local\Programs\jitsi-meet-electron\resources\app.asar\build\main.js:1:95485)
    at App.emit (events.js:187:15)
```

**Comment by saghul** [comment]
We are going to clarify this in the release notes of the final version, but this is "expected". We can no longer use the key we were using before because it belonged to Atlassian, so with the move to 8x8 we cannot keep using it.

For now, the application will be released unsigned on all platforms.

**Comment by C0rn3j** [comment]
That's understandable, so I guess the only issue is not showing that the update failed to the user, be it for this or some other reason.

**Comment by fe60** [comment]
@saghul 
Will it be ok to create another issue addressing the missing signature?
This one is about the failing update without informing the user.

**Comment by tech62** [comment]
Smartscreen on windows 10 showing a warn "unknown editor", what can i do for disappearing the message
![image](https://user-images.githubusercontent.com/16237642/83215254-cf026c00-a166-11ea-9fad-82eacf99d34a.png)

**Comment by saghul** [comment]
Closing as per https://github.com/jitsi/jitsi-meet-electron/issues/234#issuecomment-610793581
