### ISSUE TITLE
Error: Module version mismatch. Expected 50, got 76.

### ISSUE THREAD

**Issue by anistark** [jitsi/jitsi-meet-electron#266]
I'm getting the error when tried running on Mac with `node v12.5.0`.

Complete error log:

```
[1] App threw an error during load
[1] Error: Module version mismatch. Expected 50, got 76.
[1]     at Error (native)
[1]     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
[1]     at Object.Module._extensions..node (module.js:583:18)
[1]     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
[1]     at Module.load (module.js:473:32)
[1]     at tryModuleLoad (module.js:432:12)
[1]     at Function.Module._load (module.js:424:3)
[1]     at Module.require (module.js:483:17)
[1]     at require (internal/module.js:20:19)
[1]     at Object.<anonymous> (/path-to-dir/jitsi-meet-electron/node_modules/robotjs/index.js:1:94)
```

If anybody else fixed it, please advice.

**Comment by saghul** [comment]
Did you build it? We do use Node. 12 for building releases.

**Comment by anistark** [comment]
@saghul Not built it. I'm running `npm start` as stated in dev doc in Readme. 
I'm on node `v12.5.0`

**Comment by saghul** [comment]
Did you `npm install` first?

**Comment by anistark** [comment]
Of course. @saghul

**Comment by saghul** [comment]
Not ssure what's up, but I cannotreproduce it :-(

**Comment by anistark** [comment]
@akshitkrnagpal Thanks. That worked. 😄 
Much appreciated.
