### ISSUE TITLE
can't build anymore: fatal error: X11/extensions/XTest.h: No such file or directory

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet-electron#433]
Just did a fresh git clone of master and was going to build the app as usual but there seems to be a file missing XTest.h

I was able to compile the app without issues a few weeks ago so something must have changed recently. npm install complains about missing X11 file. Maybe the recent npm audit broke something?

```
CC(target) Release/obj.target/robotjs/src/mouse.o
../src/mouse.c:12:11: fatal error: X11/extensions/XTest.h: No such file or directory
   12 |  #include <X11/extensions/XTest.h>
      |           ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [robotjs.target.mk:133: Release/obj.target/robotjs/src/mouse.o] Error 1
make: Leaving directory '/home/user/Documents/development/git/jitsi-meet-electron/node_modules/robotjs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/home/user/.nvm/versions/node/v12.18.2/bin/node" "/home/user/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/Documents/development/git/jitsi-meet-electron/node_modules/robotjs
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
```

Cheers

**Comment by pdarcos** [comment]
Silly me. Forgot libxtst-dev wasn't installed.
Sorry
