### ISSUE TITLE
Installing dependencies failed

### ISSUE THREAD

**Issue by kunlk** [jitsi/jitsi-meet-electron#459]
Hi Team,

I was trying to build on Ubuntu 18.04.4 LTS, but failed when installing dependencies. I have installed libx11-dev and libxtst-dev.

root@umh:/home/ubuntu/jitsi/jitsi-meet-electron-master# npm install

> robotjs@0.6.0 install /home/ubuntu/jitsi/jitsi-meet-electron-master/node_modules/robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.19.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/home/ubuntu/jitsi/jitsi-meet-electron-master/node_modules/robotjs/build'
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
cc1plus: warning: command line option ‘-Wbad-function-cast’ is valid for C/ObjC but not for C++
../src/robotjs.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE keyToggle(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/robotjs.cc:592:17: warning: ‘down’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    toggleKeyCode(key, down, flags);
    ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:288,
                 from ../src/robotjs.cc:2:
../../nan/nan_implementation_12_inl.h: In function ‘void InitAll(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../../nan/nan_implementation_12_inl.h:119:1: warning: inlining failed in call to ‘static Nan::imp::FactoryBase<v8::FunctionTemplate>::return_t Nan::imp::Factory<v8::FunctionTemplate>::New(Nan::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>)’: --param large-function-growth limit reached [-Winline]
 Factory<v8::FunctionTemplate>::New( FunctionCallback callback
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../nan/nan.h:288:0,
                 from ../src/robotjs.cc:2:
../../nan/nan_new.h:239:47: note: called from here
     return imp::Factory<T>::New(callback, data);
                                               ^
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:288,
                 from ../src/robotjs.cc:2:
../../nan/nan_implementation_12_inl.h:119:1: warning: inlining failed in call to ‘static Nan::imp::FactoryBase<v8::FunctionTemplate>::return_t Nan::imp::Factory<v8::FunctionTemplate>::New(Nan::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>)’: --param large-function-growth limit reached [-Winline]
 Factory<v8::FunctionTemplate>::New( FunctionCallback callback
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../nan/nan.h:288:0,
                 from ../src/robotjs.cc:2:
../../nan/nan_new.h:239:47: note: called from here
     return imp::Factory<T>::New(callback, data);
                                               ^
  CC(target) Release/obj.target/robotjs/src/deadbeef_rand.o
  CC(target) Release/obj.target/robotjs/src/mouse.o
  CC(target) Release/obj.target/robotjs/src/keypress.o
../src/keypress.c: In function ‘typeString’:
../src/keypress.c:259:32: warning: ‘n’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  #define toggleUniKey(c, down) toggleKey(c, down, MOD_NONE)
                                ^~~~~~~~~
../src/keypress.c:274:16: note: ‘n’ was declared here
  unsigned long n;
                ^
  CC(target) Release/obj.target/robotjs/src/keycode.o
  CC(target) Release/obj.target/robotjs/src/screen.o
  CC(target) Release/obj.target/robotjs/src/screengrab.o
  CC(target) Release/obj.target/robotjs/src/snprintf.o
../src/snprintf.c: In function ‘portable_vsnprintf’:
../src/snprintf.c:557:33: warning: signed and unsigned type in conditional expression [-Wsign-compare]
       size_t n = !q ? strlen(p) : (q-p);
                                 ^
../src/snprintf.c:704:40: warning: signed and unsigned type in conditional expression [-Wsign-compare]
             str_arg_l = !q ? precision : (q-str_arg);
                                        ^
../src/snprintf.c:943:62: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             fast_memset(str+str_l, (zero_padding?'0':' '), (n>avail?avail:n));
                                                              ^
../src/snprintf.c:372:35: note: in definition of macro ‘fast_memset’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:943:74: warning: signed and unsigned type in conditional expression [-Wsign-compare]
             fast_memset(str+str_l, (zero_padding?'0':' '), (n>avail?avail:n));
                                                                          ^
../src/snprintf.c:372:35: note: in definition of macro ‘fast_memset’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:960:47: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             fast_memcpy(str+str_l, str_arg, (n>avail?avail:n));
                                               ^
../src/snprintf.c:365:35: note: in definition of macro ‘fast_memcpy’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:960:59: warning: signed and unsigned type in conditional expression [-Wsign-compare]
             fast_memcpy(str+str_l, str_arg, (n>avail?avail:n));
                                                           ^
../src/snprintf.c:365:35: note: in definition of macro ‘fast_memcpy’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:969:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             fast_memset(str+str_l, '0', (n>avail?avail:n));
                                           ^
../src/snprintf.c:372:35: note: in definition of macro ‘fast_memset’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:969:55: warning: signed and unsigned type in conditional expression [-Wsign-compare]
             fast_memset(str+str_l, '0', (n>avail?avail:n));
                                                       ^
../src/snprintf.c:372:35: note: in definition of macro ‘fast_memset’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:981:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                         (n>avail?avail:n));
                           ^
../src/snprintf.c:365:35: note: in definition of macro ‘fast_memcpy’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:981:39: warning: signed and unsigned type in conditional expression [-Wsign-compare]
                         (n>avail?avail:n));
                                       ^
../src/snprintf.c:365:35: note: in definition of macro ‘fast_memcpy’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:992:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             fast_memset(str+str_l, ' ', (n>avail?avail:n));
                                           ^
../src/snprintf.c:372:35: note: in definition of macro ‘fast_memset’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:992:55: warning: signed and unsigned type in conditional expression [-Wsign-compare]
             fast_memset(str+str_l, ' ', (n>avail?avail:n));
                                                       ^
../src/snprintf.c:372:35: note: in definition of macro ‘fast_memset’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:564:19: warning: variable ‘starting_p’ set but not used [-Wunused-but-set-variable]
       const char *starting_p;
                   ^~~~~~~~~~
../src/snprintf.c:369:48: warning: ‘str_arg’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       for (ss=(s), dd=(d); nn>0; nn--) *dd++ = *ss++; } }
                                                ^
../src/snprintf.c:573:19: note: ‘str_arg’ was declared here
       const char *str_arg;      /* string address in case of string argument */
                   ^~~~~~~
  CC(target) Release/obj.target/robotjs/src/MMBitmap.o
  CC(target) Release/obj.target/robotjs/src/xdisplay.o
../src/xdisplay.c: In function ‘setXDisplay’:
../src/xdisplay.c:53:16: warning: implicit declaration of function ‘strdup’ [-Wimplicit-function-declaration]
  displayName = strdup(name);
                ^~~~~~
../src/xdisplay.c:53:16: warning: incompatible implicit declaration of built-in function ‘strdup’
  SOLINK_MODULE(target) Release/obj.target/robotjs.node
/usr/bin/ld: cannot find -lpng
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
robotjs.target.mk:171: recipe for target 'Release/obj.target/robotjs.node' failed
make: *** [Release/obj.target/robotjs.node] Error 1
make: Leaving directory '/home/ubuntu/jitsi/jitsi-meet-electron-master/node_modules/robotjs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-122-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/jitsi/jitsi-meet-electron-master/node_modules/robotjs
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.0 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-03T07_50_13_171Z-debug.log

**Comment by saghul** [comment]
You are still missing some packages. Install these: https://github.com/jitsi/jitsi-meet-electron/blob/master/.travis.yml#L15
