### ISSUE TITLE
can't start this project

### ISSUE THREAD

**Issue by WildDylan** [jitsi/jitsi-meet-electron#88]
```shell
  jitsi-meet-electron git:(master) ✗ npm start

> jitsi-meet-electron@1.0.0-alpha.1 start /Users/root1/Desktop/jitsi-meet-electron
> webpack --config ./webpack.config.js --mode development && electron ./build/main.js

Hash: 320fd2532dfcf2892fa276fca7e446794b0e37dc
Version: webpack 4.8.1
Child
    Hash: 320fd2532dfcf2892fa2
    Time: 470ms
    Built at: 2018-07-16 10:28:01
      Asset      Size  Chunks             Chunk Names
    main.js  4.29 KiB    main  [emitted]  main
    Entrypoint main = main.js
    [./main.js] 1.49 KiB {main} [built] [failed] [1 error]

    ERROR in ./main.js
    Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/root1/Desktop"
        at /Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
        at Array.map (<anonymous>)
        at OptionManager.resolvePresets (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
        at OptionManager.mergePresets (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
        at OptionManager.mergeOptions (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
        at OptionManager.init (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
        at File.initOptions (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/file/index.js:212:65)
        at new File (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/file/index.js:135:24)
        at Pipeline.transform (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
        at transpile (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-loader/lib/index.js:50:20)
        at Object.module.exports (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-loader/lib/index.js:173:20)
Child
    Hash: 76fca7e446794b0e37dc
    Time: 708ms
    Built at: 2018-07-16 10:28:01
         Asset       Size  Chunks             Chunk Names
        app.js   4.32 KiB     app  [emitted]  app
    index.html  361 bytes          [emitted]
    Entrypoint app = app.js
    [./app/index.js] 1.49 KiB {app} [built] [failed] [1 error]

    ERROR in ./app/index.js
    Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/root1/Desktop"
        at /Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
        at Array.map (<anonymous>)
        at OptionManager.resolvePresets (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
        at OptionManager.mergePresets (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
        at OptionManager.mergeOptions (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
        at OptionManager.init (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
        at File.initOptions (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/file/index.js:212:65)
        at new File (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/file/index.js:135:24)
        at Pipeline.transform (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
        at transpile (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-loader/lib/index.js:50:20)
        at Object.module.exports (/Users/root1/Desktop/jitsi-meet-electron/node_modules/babel-loader/lib/index.js:173:20)
    Child html-webpack-plugin for "index.html":
         1 asset
        Entrypoint undefined = index.html
        [./node_modules/html-webpack-plugin/lib/loader.js!./app/index.html] 521 bytes {0} [built]
        [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {0} [built]
            + 1 hidden module
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! jitsi-meet-electron@1.0.0-alpha.1 start: `webpack --config ./webpack.config.js --mode development && electron ./build/main.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the jitsi-meet-electron@1.0.0-alpha.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/root1/.npm/_logs/2018-07-16T02_28_01_375Z-debug.log
```

and the log 

```
➜  jitsi-meet-electron git:(master) ✗ more /Users/root1/.npm/_logs/2018-07-16T02_28_01_375Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.1.0
3 info using node@v10.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle jitsi-meet-electron@1.0.0-alpha.1~prestart: jitsi-meet-electron@1.0.0-alpha.1
6 info lifecycle jitsi-meet-electron@1.0.0-alpha.1~start: jitsi-meet-electron@1.0.0-alpha.1
7 verbose lifecycle jitsi-meet-electron@1.0.0-alpha.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle jitsi-meet-electron@1.0.0-alpha.1~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/root1/Desktop/jitsi-meet-electron/node_modules/.bin:/Users/root1/.jenv/shims:/Users/root1/.jenv/bin:/Users/root1/torch/install/bin:/Users/root1/torch/install/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin:/Users/root1/bin:/opt/local/bin:/Users/root1/.rvm/gems/ruby-2.3.0/bin:/Users/root1/.rvm/gems/ruby-2.3.0@global/bin:/Users/root1/.rvm/rubies/ruby-2.3.0/bin:/Users/root1/.sdkman/candidates/springboot/current/bin:/Users/root1/torch/install/bin:/Users/root1/torch/install/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/root1/.rvm/bin:/Users/root1/Library/Android/android-sdk-macosx/platform-tools/:/Users/root1/apache-maven-3.5.0/bin:/Users/root1/gradle-4.3.1/bin:/Users/root1/wine-2.0.2/bin:/usr/local/mysql-5.7.18-macos10.12-x86_64/bin:/usr/local/share/scala-2.12.3/bin:/Users/root1/go/bin:/Users/root1/.rvm/bin:/Users/root1/gradle-4.1/bin
9 verbose lifecycle jitsi-meet-electron@1.0.0-alpha.1~start: CWD: /Users/root1/Desktop/jitsi-meet-electron
10 silly lifecycle jitsi-meet-electron@1.0.0-alpha.1~start: Args: [ '-c',
10 silly lifecycle   'webpack --config ./webpack.config.js --mode development && electron ./build/main.js' ]
11 silly lifecycle jitsi-meet-electron@1.0.0-alpha.1~start: Returned: code: 2  signal: null
12 info lifecycle jitsi-meet-electron@1.0.0-alpha.1~start: Failed to exec start script
13 verbose stack Error: jitsi-meet-electron@1.0.0-alpha.1 start: `webpack --config ./webpack.config.js --mode development && electron ./build/main.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid jitsi-meet-electron@1.0.0-alpha.1
15 verbose cwd /Users/root1/Desktop/jitsi-meet-electron
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.2.1
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 2
22 error jitsi-meet-electron@1.0.0-alpha.1 start: `webpack --config ./webpack.config.js --mode development && electron ./build/main.js`
22 error Exit status 2
23 error Failed at the jitsi-meet-electron@1.0.0-alpha.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by akshitkrnagpal** [comment]
@WildDylan 
Can you please verify that `babel-preset-es2015` has been installed?
Try `npm ls babel-preset-es2015`.

If not try `npm install` again.

**Comment by WildDylan** [comment]
@akshitkrnagpal thanks for your answer. 

i have fix this question. because the `father directory` hava a `.bablerc` file, remove this make me happy !
